# Generated by Django 5.0.4 on 2024-05-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('is_main', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='edition.edition')),
            ],
            options={
                'verbose_name': 'Eddition',
                'verbose_name_plural': 'Edditions',
                'db_table': 'paper_edition',
            },
        ),
    ]
