# Generated by Django 5.0.4 on 2024-05-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'verbose_name': 'Edition', 'verbose_name_plural': 'Editions'},
        ),
        migrations.AddField(
            model_name='edition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
