# Generated by Django 5.0.4 on 2024-05-16 05:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epaper', '0008_paperpage_is_variant_paperpage_parent_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_main', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('image_url', models.CharField(max_length=512)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epaper.paperpage')),
            ],
            options={
                'verbose_name': 'PaperCut',
                'verbose_name_plural': 'PaperCuts',
                'db_table': 'paper_cut',
            },
        ),
    ]
