# Generated by Django 5.0.4 on 2024-05-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_subscriber_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
