# Generated by Django 5.0.4 on 2024-05-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epaper', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperpage',
            old_name='page_number',
            new_name='page',
        ),
    ]
