# Generated by Django 5.0.4 on 2024-05-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epaper', '0003_rename_page_number_paperpage_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperpage',
            old_name='page',
            new_name='page_number',
        ),
    ]
