# Generated by Django 5.0.4 on 2024-05-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epaper', '0004_rename_page_paperpage_page_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperpage',
            name='page_number',
        ),
    ]
