# Generated by Django 5.0.4 on 2024-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epaper', '0005_remove_paperpage_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperpage',
            name='page_number',
            field=models.IntegerField(default=999),
        ),
    ]
