# Generated by Django 5.0.4 on 2024-05-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epaper', '0006_paperpage_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperpage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
