# Generated by Django 5.0.4 on 2024-05-12 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edition', '0002_alter_edition_options_edition_is_active'),
        ('epaper', '0007_paperpage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperpage',
            name='is_variant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paperpage',
            name='parent_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epaper.paperpage'),
        ),
        migrations.AddField(
            model_name='paperpage',
            name='sub_edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edition.edition'),
        ),
    ]
